### ISSUE TITLE
java.lang.SecurityException: Injecting to another application requires INJECT_EVENTS permission

### ISSUE THREAD

**Issue by loki666** [philburk/android-midisuite#21]
I'm still getting this SecurityException when closing the Synth Activity

**Comment by philburk** [comment]
Sometimes these SecurityExceptions happen even though I honor the window focus.
So I catch them and turn off the fake key generator.
The source code and the play store app are now updated.

https://github.com/philburk/android-midisuite/pull/22

**Comment by loki666** [comment]
arf...

didn't catch that 😁

**Comment by philburk** [comment]
?? I had changed the code but forgot to upload it.  I uploaded it after your bug report. Your bug report reminded me. Thanks.
