### ISSUE TITLE
MidiKeyboard: still getting multiple onDeviceStatusChanged() on rotation

### ISSUE THREAD

**Issue by loki666** [philburk/android-midisuite#23]
`08-08 10:45:31.439 12717-12717/? I/MidiTools: MidiPortSelector.onDeviceStatusChanged status = mInputPortOpen=[true] mOutputPortOpenCount=[], mType = 1, activity = com.mobileer.midikeyboard, info = MidiDeviceInfo[mType=2,mInputPortCount=1,mOutputPortCount=0,mProperties=Bundle[{manufacturer=Volcano Mobile, product=Wavetable Synth, service_info=ServiceInfo{1acc375 net.volcanomobile.sonivoxeasmidi.MidiSynthDeviceService}}],mIsPrivate=false
08-08 10:45:31.440 12717-12717/? I/MidiTools: MidiPortSelector.onDeviceStatusChanged status = mInputPortOpen=[true] mOutputPortOpenCount=[], mType = 1, activity = com.mobileer.midikeyboard, info = MidiDeviceInfo[mType=2,mInputPortCount=1,mOutputPortCount=0,mProperties=Bundle[{manufacturer=Volcano Mobile, product=Wavetable Synth, service_info=ServiceInfo{b9b0f0a net.volcanomobile.sonivoxeasmidi.MidiSynthDeviceService}}],mIsPrivate=false
08-08 10:45:31.441 12717-12717/? I/MidiTools: MidiPortSelector.onDeviceStatusChanged status = mInputPortOpen=[true] mOutputPortOpenCount=[], mType = 1, activity = com.mobileer.midikeyboard, info = MidiDeviceInfo[mType=2,mInputPortCount=1,mOutputPortCount=0,mProperties=Bundle[{manufacturer=Volcano Mobile, product=Wavetable Synth, service_info=ServiceInfo{b56a37b net.volcanomobile.sonivoxeasmidi.MidiSynthDeviceService}}],mIsPrivate=false
08-08 10:45:31.442 12717-12717/? I/MidiTools: MidiPortSelector.onDeviceStatusChanged status = mInputPortOpen=[true] mOutputPortOpenCount=[], mType = 1, activity = com.mobileer.midikeyboard, info = MidiDeviceInfo[mType=2,mInputPortCount=1,mOutputPortCount=0,mProperties=Bundle[{manufacturer=Volcano Mobile, product=Wavetable Synth, service_info=ServiceInfo{5d54598 net.volcanomobile.sonivoxeasmidi.MidiSynthDeviceService}}],mIsPrivate=false
08-08 10:45:31.443 12717-12717/? I/MidiTools: MidiPortSelector.onDeviceStatusChanged status = mInputPortOpen=[true] mOutputPortOpenCount=[], mType = 1, activity = com.mobileer.midikeyboard, info = MidiDeviceInfo[mType=2,mInputPortCount=1,mOutputPortCount=0,mProperties=Bundle[{manufacturer=Volcano Mobile, product=Wavetable Synth, service_info=ServiceInfo{29321f1 net.volcanomobile.sonivoxeasmidi.MidiSynthDeviceService}}],mIsPrivate=false
08-08 10:45:31.443 12717-12717/? I/MidiTools: MidiPortSelector.onDeviceStatusChanged status = mInputPortOpen=[true] mOutputPortOpenCount=[], mType = 1, activity = com.mobileer.midikeyboard, info = MidiDeviceInfo[mType=2,mInputPortCount=1,mOutputPortCount=0,mProperties=Bundle[{manufacturer=Volcano Mobile, product=Wavetable Synth, service_info=ServiceInfo{e6311d6 net.volcanomobile.sonivoxeasmidi.MidiSynthDeviceService}}],mIsPrivate=false
`

**Comment by philburk** [comment]
I probably need to call 
        mLogSenderSelector.onDestroy();
after
        mLogSenderSelector.onClose();
in the MainActivity. I don't have a cable with me. Will try to fix ASAP.
Thanks for reporting this.
