### ISSUE TITLE
publish miditools on jcenter

### ISSUE THREAD

**Issue by loki666** [philburk/android-midisuite#30]

**Comment by philburk** [comment]
JCenter is a Maven repo that Android Studio can easily load libraries from.
This website describes how to load a library into JCenter:

https://inthecheesefactory.com/blog/how-to-upload-library-to-jcenter-maven-central-as-dependency/en

**Comment by loki666** [comment]
I know, the issue is about that you, the owner of this library, upload it.

**Comment by philburk** [comment]
Right. I had not heard of JCenter so I looked it up and made a note for myself . Before fixing a bug I often gather background information. That way I know what is required to address it.

**Comment by loki666** [comment]
Ah OK.
I'll see if I can make a PR.

**Comment by philburk** [comment]
What is a PR? We may be transferring the android-midisuite into a Google account. So it might be better to post on JCenter after the transfer. I'll check with the Android Studio folks.

**Comment by loki666** [comment]
Pull Request
