### ISSUE TITLE
Contribution App

### ISSUE THREAD

**Issue by cags12** [philburk/android-midisuite#37]
Hi - I have used your code for creating a simple app based on MidiScope that bridges input ports to output ports. This combined to MIDI-BTLE gives access to MIDI BTLE to systems that are only USB-MIDI compliant.

The code is ready and I'm looking for guidance on making this contribution as I'd like to see this in the Play Store.

**Comment by philburk** [comment]
I just had someone ask me 5 minutes ago if there was an app that could bridge between MIDI devices. I would love to see you make this into your own app and publish it.

You will need to change the package name from "com.mobileer" to your own domain.
You will also need to supply your own logo so it looks different.

You might find these links helpful.

  https://developer.android.com/studio/publish/index.html
  https://developer.android.com/distribute/best-practices/launch/launch-checklist.html

This part of GitHub is for reporting bugs. If you just want to discuss the Android MIDI API and publishing MIDI apps then the "android-midi" Google group is a good place.

  https://groups.google.com/forum/#!forum/android-midi

**Comment by AlanOsta** [comment]
Hi cags12, I wrote Phil looking for the app you made. If I can help you in anyway just let me now and I´ll be glad to contribute. I´d love to see that app on the Play Store.

**Comment by cags12** [comment]
Hi Phil - Thank you, I used this facility of Github because on the "CONTRIBUTING" file it said so. I will open a thread on the "andoid-midi" Google group so we can discuss further,

AlanOsta - I can send you a per-liminar APK file for you to test while I work to publish the app in the Play store.

**Comment by AlanOsta** [comment]
That would be great Christian, how do I get in touch with you?

**Comment by philburk** [comment]
I have Alan's email address but I don't have cags12's address.  Please don't put your email addresses in this forum. You might get spam.

@cags12 - you can send me an email though my contacts page at: http://www.softsynth.com/contacts.php

Then I can send your address to Alan.

**Comment by philburk** [comment]
cags12 wrote "I used facility of Github because on the "CONTRIBUTING" file it said so."

Right. Sorry. That is for contributing code or bug fixes directly into this repository, which requires signing a Google Contributor License. But in your case you are really building a new app based on this code, which is wonderful. You can do that without signing anything because this code is under Apache 2 Open Source License.

**Comment by cags12** [comment]
Thank you Phil,

Alan already contacted me directly and I sent the test apk. 

I opened a topic in  the "android-midi" Google group, I have some bits to discuss further and it seems you are the best person to talk to :)
