### ISSUE TITLE
Role of MidiFramer

### ISSUE THREAD

**Issue by audetto** [philburk/android-midisuite#54]
Trying to understand the way MidiFramer handles SysEx messages.

If a long SysEx arrives, is the MidiFramer goal to present it to the next MidiReceiver as a single package?

My piano sends back a 30 byte SysEx message, but the MidiFramer sends it back in 3 tranches.
Before investigating more, whose role would it be to make it a single long SysEx message?

**Comment by philburk** [comment]
MidiFramer will pass on the SysEx data in one or more pieces of arbitrary size.
If a real-time message comes in then the SysEx data will be sent in one call to send() followed by another call with the real-time message.
If you want to aggregate all of the SysEx data then you will need to do that in your app. It may be very large!

The main role of MidiFramer is to resolve running status and to align arbitrary bytes into one regular command per call.
