### ISSUE TITLE
USB MIDI would stop functioning after sometimes

### ISSUE THREAD

**Issue by bhaskar-c** [philburk/android-midisuite#60]
Hi

I built an app https://play.google.com/store/apps/details?id=com.humtools.midikontrol
This is based on your MIDI synthesizer example. For USB interfacing, I have used your code verbatim. 

However a lot of users have been complaining that the app disconnects after around 10 minutes. And this is on various devices as reported by users.

Here are two of the reviews (and many others have reported a similar thing):

> After 10 minutes of testing this app on Bitwig, it throws a message saying "Please connect a valid Midi receiver through the MIDI port on your device". Meaning the phone stopped working as a Midi device, tested with different cables with the same result on a Samsung Galaxy Note 8. 

Another review:

> I wanted to report one little bug. Sometimes when using the app it stops sending MIDI to computer. Mostly it happens after leaving the app for a moment and going back into it. 
> When it stops sending MIDI I discovered the whole USB functions in Android doesn't work anymore. Then I have to restart my phone to make it work again.

I am at a loss as to why this should happen. 

Any suggestions would be helpful.
I can share the entire source code if you so wish.

regards

**Comment by philburk** [comment]
What were you connecting to?
Were you using the app to control a laptop? Mac or Windows?
Do you also see this disconnect if you use my midi keyboard app from the play store?
What are the exact steps that I can follow to reproduce this bug?

**Comment by philburk** [comment]
no answer - obsolete
