### ISSUE TITLE
gradle-6.7.1 is too old , when I check out poject I have to update to build it.. 

### ISSUE THREAD

**Issue by renetik** [philburk/android-midisuite#79]
gradle-6.7.1 is too old , when I check out poject I have to update to build it..

**Comment by philburk** [comment]
PR #78 brings this project up-to-date.
This was needed so I could update the apps on the Play Store, which I am working on now.

And yes, you will probably need to update your gradle. I am using gradle 7.5.

I once tried upgrading to gradle 8.0.2 but I ran into many problems with the build and mismatches between the JDK version that I was unable to solve. So I do not recommend that.
