### ISSUE TITLE
Opening port does not open connection with Macbook advertiser

### ISSUE THREAD

**Issue by renetik** [philburk/android-midisuite#80]
I came here after strugling with this in my own use of this android api. I see the same behaviour with you code here. For me it seems gthat android bluetooth midi scanner input device output port is broken or not compatible some android versions.
I tested it on Samsun Galaxy tab 6 lite android 13  TP1A
I also tested with same behaviour on Androiud 11 Xiaomi M9T

Setp to reproduce:
Start bluetooth advertise on MacOS. Open MIDI+BTLE start scan connect, open sytnh set port , toas ok displays.. 
On macos nothing changes and device is not accesible.

I open Gadget on ipad, bluetooth midi devices , connect to same macbook , device opens up midi studio and is accesible in ableton live. 

Android just dont work at all with macbook/macos for me. 

Is there any solution ? I have see one difference that pairing dialog popped up for ipad but not android devices.

**Comment by philburk** [comment]
BLE-MIDI can operate in Central Mode or Peripheral mode.
Peripherals can connect to Central devices.

I believe that the Macbook and Android device are both operating in Central Mode.
So they cannot connect to each other.

Your iPad and BLE-MIDI keyboards are acting in Peripheral Mode so they can connect to Android or the Macbook.

**Comment by renetik** [comment]
Macbook operates in both modes, its very easy UI in MacOS "Audio Midi Setup" I was hoping you know such details when you are author of this midi suite. On the other hand I implemented peripherial and also central o android. Sadly central is not working correctly. Neather your simple code from here nor kshoji https://github.com/kshoji/BLE-MIDI-for-Android . I was hopping you got more insights, if not you can leave this closed then. 
Actually its not that is not working at all but with macbook looks like there is some incompatibility. Just peripherial code from peripherial kshoji is truely multiplatform. In my testing when I used on one android device kshoji perpherial and on toher android device standard central it worked.  I believe android is buggy as ios ble midi is used a lot in multiple apps.
